### ISSUE TITLE
Geringerer Wiederstand bei IR LED nutzen

### ISSUE THREAD

**Issue by romulus-ai** [PhilippHee/VentilatorSteuerung-Alexa-ESP8266#1]
Hey, das Projekt und die Schaltung finde ich wirklich klasse, habe das als Basis für ein MQTT + HTTP basiertes Projekt genutzt. Mir ist allerdings aufgefallen, dass die LED mit 100mA betrieben werden kann, hier brauche ich nämlich eine bedeutend höhere Reichweite als 10cm.

Wenn ich mich nun nicht verrechnet habe, Sie wird ja am 3V Anschluss betrieben, 1,2V benötigt ja die LED, bleiben also noch 1,8V über, wenn ich nun auf 1,8V / 0,1A = 18 Ohm, folglich müsste der 680 Ohm Wiederstand auf 18 Ohm reduziert werden um die Sendeleistung zu erhöhen.

Da ich nun leider keine 1 Ohm Wiederstände habe, hab ich einfach mal 2 10 Ohm Wiederstände eingesetzt, damit konnte ich die Reichweite nun auf ca. 3m erweitern. Zusammen mit dem Abstrahlwinkel von 50° den die LED hat, ist hier ein super Gerät rausgekommen, mit dem man auch mehrere Geräte zuhause Fernsteuern kann!

Issue ist es ja nicht, da es hier keine Kommentarfunktion gibt, dachte ich, ich weise mal hierrüber darauf hin.

**Comment by PhilippHee** [comment]
Sorry, bin jetzt erst dazu gekommen, den Schaltplan anzupassen. Danke für den Hinweis. Ich habe den Widerstand jetzt nochmal mit den typischen Werten aus dem Datenblatt berechnet:

R1 = (3,3 V - 1,2 V) / 20 mA = 105 Ohm -> 100 Ohm

(Auf dem Board steht beim Anschluss 3V oder 3V3. Der Anschluss hat aber immer 3,3 V.)
